2023-01-06 17:02:07 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014217B74220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
2023-01-06 17:02:19 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014217DE43D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
2023-01-06 18:34:51 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014217DF5A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
